[package]
name = "smart-home_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
thiserror = "2.0.11"
smart-home_tcp-client = { path = "../smart-home_tcp" }

[[bin]]
name = "smart-home-gui"
path = "src/bin/gui.rs"
