[workspace]
resolver = "2"

members = [
  "smart-home",
  "smart-home_tcp",
  "smart-home_udp",
  "smart-home_async",
  "smart-home_web",
  "smart-home_gui",
  "smart-home_ffi",
  "oop-patterns",
  "rust-patterns",
]
