[package]
name = "smart-home_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
smart-home_tcp-client = { path = "../smart-home_tcp" }

[dev-dependencies]
libloading = "0.8.6"